version: '3.4'
services:
  database:
    image: postgres:13
    container_name: blockscout_db
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: blockscout
      POSTGRES_PASSWORD: blockscout
      POSTGRES_DB: blockscout

  web:
    build: ../blockscout
    ports:
      - "4000:4000"
    depends_on:
      - "database"
      - "geth"
    environment:
      MIX_ENV: prod
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_HTTP_URL: http://geth:8545
      BLOCKSCOUT_PROTOCOL: http
      ECTO_USE_SSL: "false"
      CHAIN_ID: 53371
      PORT: 4000
      DATABASE_URL: postgresql://blockscout:blockscout@database:5432/blockscout

  geth:
    build: ../geth
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - /geth/data
